services:

    #
    # Object Managers
    #
    elcodi.object_manager.variant:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            attribute_namespace: %elcodi.core.variant.entity.variant.class%

    #
    # Object Managers
    #
    elcodi.object_manager.variant.product:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            attribute_namespace: %elcodi.core.variant.entity.product.class%