services:

    #
    # Repositories
    #

    #
    # Repository for Variant entities
    #
    elcodi.core.variant.repository.variant:
        class: %elcodi.core.variant.repository.variant.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.variant.entity.variant.class%

    elcodi.repository.variant:
        alias: elcodi.core.variant.repository.variant

    #
    # Repository for Product with variants entities
    #
    elcodi.core.variant.repository.product:
        class: %elcodi.core.variant.repository.product.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.variant.entity.product.class%

    elcodi.repository.variant.product:
        alias: elcodi.core.variant.repository.product