services:

    #
    # Repositories
    #

    #
    # Repository for Attribute entities
    #
    elcodi.core.attribute.repository.attribute:
        class: %elcodi.core.attribute.repository.attribute.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.attribute.entity.attribute.class%

    elcodi.repository.attribute:
        alias: elcodi.core.attribute.repository.attribute

    #
    # Repository for Value entities
    #
    elcodi.core.attribute.repository.value:
        class: %elcodi.core.attribute.repository.value.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.attribute.entity.value.class%

    elcodi.repository.value:
        alias: elcodi.core.attribute.repository.value